# REF: https://hatch.pypa.io/1.9/config/build/
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]

packages = [
    "a/",
    "b/",
]

[project]
name = "test-repo"
description = "test-repo package"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

readme = {file = "README.md", content-type = "text/markdown"}
requires-python = "> 3.9.7, <4.0"
version = "0.0.1"
dependencies = [
    "ruff==0.8.3",
]
authors = []
maintainers = []

[project.urls]
Repository = "https://github.com/yudgnahk/test-repo"
Issues = "https://github.com/yudgnahk/test-repo/issues"

[tool.ruff]
line-length = 120
exclude = ["__init__.py"]
