name: Check secret workflow
on:
    pull_request:
        branches:
            - dev
jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up env
              run: |
                echo "NAME=${{ secrets.NAME }}" >> $GITHUB_ENV
            - name: Check env
              if: ${{ env.NAME == '' }} 
              run: |
                echo "NAME not found"
                exit 1
            - name: Check env
              if: ${{ env.NAME != '' }}
              run: |
                    echo "NAME found"