name: Reusable workflow to print branch, tag and get some variables from github environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run the workflow in'
        required: true
        default: 'dev'
        type: string
      type:
        description: 'Type of event to trigger the workflow'
        required: true
        # Could be 'alpha', 'beta' or 'gamma'
        default: 'alpha' 
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set VAR_NAME based on type
        run: |
          if [[ "${{ inputs.type }}" == 'alpha' ]]; then
            echo "Setting ALPHA_NAME"
            echo "VAR_NAME=ALPHA_NAME" >> $GITHUB_ENV
          elif [[ "${{ inputs.type }}" == 'beta' ]]; then
            echo "Setting BETA_NAME"
            echo "VAR_NAME=BETA_NAME" >> $GITHUB_ENV
          elif [[ "${{ inputs.type }}" == 'gamma' ]]; then
            echo "Setting GAMMA_NAME"
            echo "VAR_NAME=GAMMA_NAME" >> $GITHUB_ENV
          else
            echo "Type is not valid"
            exit 1
          fi
        
      - name: Print branch, tag and get some variables from github environment
        # Using VAR_NAME set in the previous step to get the value from github environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Branch: ${{ github.ref }}"
          echo "Tag: ${{ github.ref_name }}"
          echo "VAR_NAME: ${{ env.VAR_NAME }}"
          echo "ENV VAR: ${{ env[env.VAR_NAME] }}"