name: "Migration"
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        type: string
        required: true

jobs:
  migration:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Test workflow_dispatch
        run: echo "Hello ${{ github.event.inputs.name }}"
