name: "Test dir change"
on:
  pull_request:
    branches: [dev, master]
    paths:
      - "a/**"
      - "b/**"
jobs:
  test_dir_change:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f
      - name: Loop over changed files and get its directory
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "File: $file"
            echo "Directory: $(dirname $file)"
          done
