name: Workflow dispatch on dev branch
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name to say hello to'
                required: true
                default: 'Kelvin'
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Run a one-line script
              run: echo Hello, world! My name is ${{ github.event.inputs.name }}
