name: Workflow dispatch on dev branch
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name to say hello to'
                required: true
                default: 'Kelvin'
                type: string
    pull_request:
        branches:
            - dev
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Run a one-line script
              run: echo Hello, world! My name iss ${{ github.event.inputs.name }}

